import test from "node:test";
import crypto from "node:crypto";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import net from "node:net";
import {spawn,execFileSync,execFile} from "node:child_process";
import {promisify} from "node:util";
import {once} from "node:events";
import {WebSocket} from "ws";

test("Viewer authenticates imports, presents requests, persists exact user crops and rejects resubmission",{timeout:60000},async()=>{
 const temp=fs.mkdtempSync(path.join(os.tmpdir(),"isp-viewer-"));const probe=net.createServer().listen(0,"127.0.0.1");await once(probe,"listening");const port=probe.address().port;await new Promise(r=>probe.close(r));
 const child=spawn(process.execPath,["server/index.mjs"],{env:{...process.env,ISP_WORKSPACE:temp,ISP_STATE_HOME:path.join(temp,"state"),PORT:String(port)},windowsHide:true,stdio:["ignore","pipe","pipe"]});const exited=once(child,"exit");let socket;
 const external=path.join(os.tmpdir(),`external image ${path.basename(temp)}.raw`);
 try{
  await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error("Startup timeout")),15000);child.stdout.on("data",d=>{if(String(d).includes("ISP Block Maker")){clearTimeout(timer);resolve();}});});
  const base=`http://127.0.0.1:${port}`,boot=await(await fetch(base+"/api/bootstrap")).json();const headers={Authorization:`Bearer ${boot.token}`,"Content-Type":"application/json"};
  const post=(route,body)=>fetch(base+"/api"+route,{method:"POST",headers,body:JSON.stringify(body)});
  assert.equal((await fetch(base+"/api/viewer")).status,401);
  const data=Buffer.alloc(8*8*2);for(let i=0;i<64;i++)data.writeUInt16LE(i*7,i*2);fs.writeFileSync(path.join(temp,"input.raw"),data);const spec={format:"raw",width:8,height:8,bitDepth:10,pattern:"GRBG",group:4};fs.writeFileSync(path.join(temp,"spec.json"),JSON.stringify(spec));
  fs.writeFileSync(external,data);
  const externalImport=JSON.parse(execFileSync(process.execPath,[path.join(temp,".isp/tools/isp.mjs"),"viewer-import",external,"--spec","spec.json"],{cwd:temp,windowsHide:true,encoding:"utf8"}));
  assert.deepEqual(fs.readFileSync(external),data);
  assert.deepEqual(fs.readFileSync(path.join(temp,".isp/viewer",externalImport.id+".bin")),data);
  fs.writeFileSync(external,Buffer.alloc(data.length));
  assert.deepEqual(fs.readFileSync(path.join(temp,".isp/viewer",externalImport.id+".bin")),data);
  assert.equal((await post("/viewer/images/import",{path:os.tmpdir(),spec})).status,400);
  assert.equal((await post("/viewer/images/import",{path:external,spec:{format:"bmp"}})).status,400);
  const imported=JSON.parse(execFileSync(process.execPath,[path.join(temp,".isp/tools/isp.mjs"),"viewer-import","input.raw","--spec","spec.json"],{cwd:temp,windowsHide:true,encoding:"utf8"}));
  const upload=await fetch(base+"/api/viewer/images",{method:"POST",headers:{Authorization:`Bearer ${boot.token}`,"Content-Type":"application/octet-stream","X-Image-Metadata":encodeURIComponent(JSON.stringify({name:"uploaded.raw",spec}))},body:data});assert.equal(upload.status,201);assert.equal((await upload.json()).sha256,imported.sha256);
  const opened=JSON.parse(execFileSync(process.execPath,[path.join(temp,'.isp/tools/isp.mjs'),'viewer-open','input.raw','--spec','spec.json'],{cwd:temp,windowsHide:true,encoding:'utf8'}));
  assert.equal(opened.image.reused,true);assert.equal(opened.displayed,false);assert.equal(opened.delivered,0);assert.equal(opened.command.imageId,opened.image.id);
  const reopened=JSON.parse(execFileSync(process.execPath,[path.join(temp,'.isp/tools/isp.mjs'),'viewer-open','input.raw','--spec','spec.json','--wait','0'],{cwd:temp,windowsHide:true,encoding:'utf8'}));assert.equal(reopened.image.id,opened.image.id);
  socket=new WebSocket(`ws://127.0.0.1:${port}/ws?token=${boot.token}`);await once(socket,"open");
  const presented=new Promise(resolve=>socket.on("message",d=>{const m=JSON.parse(d);if(m.type==="present")resolve(m.presentation);}));
  const request=await(await post("/viewer/requests",{imageId:imported.id,prompt:"Select flat area",blockId:"input"})).json();assert.equal(request.status,"pending");assert.equal((await presented).requestId,request.id);
  assert.equal((await post(`/viewer/requests/${request.id}/submit`,{x:7,y:7,width:2,height:2})).status,400);
  assert.equal((await post(`/viewer/requests/${request.id}/submit`,{x:1,y:2,width:3,height:2})).status,400);
  const waiting=promisify(execFile)(process.execPath,[path.join(temp,".isp/tools/isp.mjs"),"viewer-result",request.id,"--wait","5"],{cwd:temp,windowsHide:true});
  const result=await(await post(`/viewer/requests/${request.id}/submit`,{x:0,y:0,width:8,height:8})).json();assert.equal(result.status,"submitted");assert.deepEqual(result.result.output.cfaOrigin,{x:0,y:0});
  assert.equal(JSON.parse((await waiting).stdout).status,"submitted");
  const crop=fs.readFileSync(path.join(temp,result.result.paths.crop));assert.equal(crop.readUInt16LE(),0);assert.equal(crop.length,128);
  assert.equal((await post(`/viewer/requests/${request.id}/submit`,{x:0,y:0,width:1,height:1})).status,409);
  const downloaded=await fetch(base+`/api/viewer/requests/${request.id}/files/crop`,{headers});assert.deepEqual(Buffer.from(await downloaded.arrayBuffer()),crop);
  const preview=await(await fetch(base+`/api/viewer/images/${imported.id}/preview`,{headers})).json();assert.match(preview.url,/^data:image\/png;base64,/);
  const view={imageId:imported.id,render:{mode:'simple',gamma:2.2,black:0,white:1023},zoom:2,area:{x:0,y:0,width:8,height:8},visible:{x:1,y:1,width:3,height:3},highlights:[{x:1,y:1,width:2,height:2,label:'edge'}]};
  const command=await(await post('/viewer/commands',{imageId:imported.id,zoom:2,center:{x:3,y:3},render:view.render,highlights:view.highlights,show:false})).json();assert.equal(command.status,'pending');assert.equal(command.delivered,0);
  assert.equal((await post('/viewer/commands',{imageId:imported.id,center:{x:8,y:0}})).status,400);
  assert.equal((await post('/viewer/commands',{imageId:imported.id,highlights:[{x:7,y:0,width:2,height:1}]})).status,400);
  const sessionId=crypto.randomUUID();assert.equal((await post(`/viewer/commands/${command.id}/ack`,{status:'applied',sessionId})).status,200);
  assert.equal((await fetch(base+'/api/viewer/current/attachment',{headers})).status,409);
  assert.equal((await post('/viewer/view',{...view,sessionId,png:preview.url})).status,200);
  const currentImage=await(await fetch(base+'/api/viewer/current/attachment?vision=true',{headers})).json();assert.equal(currentImage.content[1].data,preview.url.split(',')[1]);
  assert.ok(fs.existsSync(currentImage.live.paths.image));
  const moved={...view,visible:{x:2,y:2,width:2,height:2}};
  await post('/viewer/view',{...moved,sessionId,png:preview.url});
  const currentAgain=await(await fetch(base+'/api/viewer/current/attachment',{headers})).json();assert.equal(currentAgain.live.paths.image,currentImage.live.paths.image);assert.deepEqual(currentAgain.live.visible,moved.visible);
  assert.equal((await(await fetch(base+'/api/viewer/view',{headers})).json()).snapshots.length,0);
  const currentCli=JSON.parse(execFileSync(process.execPath,[path.join(temp,'.isp/tools/isp.mjs'),'viewer-image'],{cwd:temp,windowsHide:true,encoding:'utf8'}));assert.equal(currentCli.live.imageId,imported.id);
  assert.equal((await(await fetch(base+`/api/viewer/commands/${command.id}`,{headers})).json()).status,'applied');
  assert.equal((await post('/viewer/view',{...view,sessionId})).status,200);
  assert.deepEqual((await(await fetch(base+'/api/viewer/view',{headers})).json()).live.visible,view.visible);
  await post('/viewer/view/hidden',{sessionId:crypto.randomUUID()});
  assert.ok((await(await fetch(base+'/api/viewer/view',{headers})).json()).live);
  await post('/viewer/view/hidden',{sessionId});
  assert.equal((await fetch(base+'/api/viewer/current/attachment',{headers})).status,409);
  const screen=await(await post('/viewer/views',{view,note:'Check this rendered view, not a crop',png:preview.url})).json();assert.ok(screen.id);
  assert.deepEqual(fs.readFileSync(screen.paths.image),Buffer.from(preview.url.split(',')[1],'base64'));
  const withoutVision=await(await fetch(base+`/api/viewer/views/${screen.id}/attachment`,{headers})).json();assert.equal(withoutVision.imageSupported,false);assert.equal(withoutVision.content,undefined);
  const withVision=await(await fetch(base+`/api/viewer/views/${screen.id}/attachment?vision=true`,{headers})).json();assert.equal(withVision.content[1].type,'image');assert.equal(withVision.content[1].data,preview.url.split(',')[1]);
  assert.equal((await post('/viewer/views',{view:{...view,visible:{x:7,y:0,width:2,height:1}},png:preview.url})).status,400);
  assert.equal((await post('/viewer/views',{view,png:'data:image/png;base64,Zm9v'})).status,400);
  const cliScreen=JSON.parse(execFileSync(process.execPath,[path.join(temp,'.isp/tools/isp.mjs'),'viewer-image',screen.id],{cwd:temp,windowsHide:true,encoding:'utf8'}));assert.equal(cliScreen.snapshot.id,screen.id);
  assert.equal((await fetch(base+`/api/viewer/views/${screen.id}`,{method:'DELETE',headers,body:'{}'})).status,200);assert.equal(fs.existsSync(screen.paths.image),false);assert.ok(fs.existsSync(path.join(temp,'input.raw')));
  const multi=await(await post("/viewer/requests",{imageId:imported.id,prompt:"여러 영역",show:false})).json();
  const firstId=crypto.randomUUID(),secondId=crypto.randomUUID(),roi={x:0,y:0,width:8,height:8};
  const first=await(await post(`/viewer/requests/${multi.id}/crops`,{id:firstId,roi})).json();assert.equal(first.crops.length,1);assert.equal(first.status,"submitted");
  const duplicate=await(await post(`/viewer/requests/${multi.id}/crops`,{id:firstId,roi})).json();assert.equal(duplicate.crops.length,1);
  const second=await(await post(`/viewer/requests/${multi.id}/crops`,{id:secondId,roi,description:"두 번째"})).json();assert.equal(second.crops.length,2);assert.notEqual(second.crops[0].paths.crop,second.crops[1].paths.crop);
  const selection={imageId:imported.id,items:[{requestId:multi.id,cropId:firstId},{requestId:multi.id,cropId:secondId}]};
  const sent=await(await post('/viewer/crop-selection',selection)).json();assert.equal(sent.crops.length,2);assert.deepEqual(sent.missing,[]);
  assert.equal((await post('/viewer/crop-selection',{...selection,items:[selection.items[0],selection.items[0]]})).status,400);
  assert.equal((await post('/viewer/crop-selection',{...selection,items:[{requestId:multi.id,cropId:crypto.randomUUID()}]})).status,409);
  const edited=await fetch(base+`/api/viewer/requests/${multi.id}/crops/${firstId}`,{method:"PATCH",headers,body:JSON.stringify({description:"평탄 영역 테스트",previousDescription:""})});assert.equal(edited.status,200);
  const described=await edited.json();assert.equal(described.crops[0].description,"평탄 영역 테스트");assert.equal(described.result.description,"평탄 영역 테스트");
  assert.equal(JSON.parse(fs.readFileSync(path.join(temp,described.crops[0].paths.metadata),"utf8")).description,"평탄 영역 테스트");
  const selectedRead=JSON.parse(execFileSync(process.execPath,[path.join(temp,'.isp/tools/isp.mjs'),'viewer-crops'],{cwd:temp,windowsHide:true,encoding:'utf8'}));assert.equal(selectedRead.crops[0].description,'평탄 영역 테스트');
  assert.equal((await fetch(base+`/api/viewer/requests/${multi.id}/crops/${firstId}`,{method:"PATCH",headers,body:JSON.stringify({description:"stale",previousDescription:""})})).status,409);
  const multiDownload=await fetch(base+`/api/viewer/requests/${multi.id}/files/crop?cropId=${secondId}`,{headers});assert.equal(multiDownload.status,200);assert.deepEqual(Buffer.from(await multiDownload.arrayBuffer()),data);
  const multiRead=JSON.parse(execFileSync(process.execPath,[path.join(temp,".isp/tools/isp.mjs"),"viewer-result",multi.id],{cwd:temp,windowsHide:true,encoding:"utf8"}));assert.equal(multiRead.crops.length,2);assert.equal(multiRead.crops[0].description,"평탄 영역 테스트");
  const removed=await fetch(base+`/api/viewer/requests/${multi.id}/crops/${firstId}`,{method:"DELETE",headers,body:"{}"});assert.equal(removed.status,200);
  const afterRemove=await removed.json();assert.equal(afterRemove.crops.length,1);assert.equal(afterRemove.result.id,secondId);
  const remainingSelection=await(await fetch(base+'/api/viewer/crop-selection',{headers})).json();assert.equal(remainingSelection.crops.length,1);assert.equal(remainingSelection.missing.length,1);
  for(const file of Object.values(described.crops[0].paths))assert.equal(fs.existsSync(path.join(temp,file)),false);
  assert.equal(fs.existsSync(path.join(temp,"input.raw")),true);
  assert.equal((await fetch(base+`/api/viewer/requests/${multi.id}/files/crop?cropId=${firstId}`,{headers})).status,400);
  const lastRemoved=await(await fetch(base+`/api/viewer/requests/${multi.id}/crops/${secondId}`,{method:"DELETE",headers,body:"{}"})).json();assert.equal(lastRemoved.status,"pending");assert.equal(lastRemoved.crops.length,0);assert.equal(lastRemoved.result,undefined);
  assert.equal((await fetch(base+`/api/viewer/requests/${multi.id}/crops/${secondId}`,{method:"DELETE",headers,body:"{}"})).status,404);
  const cancelled=await(await post("/viewer/requests",{imageId:imported.id,prompt:"Cancel me",show:false})).json();await post(`/viewer/requests/${cancelled.id}/cancel`,{});assert.equal((await post(`/viewer/requests/${cancelled.id}/submit`,{x:0,y:0,width:1,height:1})).status,409);
  assert.equal((await post(`/viewer/requests/${cancelled.id}/crops`,{id:crypto.randomUUID(),roi})).status,409);
  assert.equal(JSON.parse(fs.readFileSync(path.join(temp,".isp/viewer/requests.json"),"utf8"))[0].status,"submitted");
 }finally{if(fs.existsSync(external))fs.unlinkSync(external);socket?.terminate();child.kill();await exited;fs.rmSync(temp,{recursive:true,force:true});}
});
