import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import os from 'node:os';
import express from 'express';
import {z} from 'zod';
import {safeName,writeZip,openZip} from './bundle-zip.mjs';

const digest=value=>crypto.createHash('sha256').update(value).digest('hex');
const nameSchema=z.string().regex(/^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$/).max(64);
const versionSchema=z.string().regex(/^[a-f0-9]{64}$/).nullable();
const payloadSchema=z.object({name:nameSchema,files:z.record(z.string(),z.string()),version:versionSchema});
const MAX_TOTAL=10*1024*1024;
function safe(w,relative){safeName(relative);let target=path.resolve(w);for(const part of relative.split('/')){target=path.join(target,part);try{if(fs.lstatSync(target).isSymbolicLink())throw Error('Linked skill paths are not supported');}catch(e){if(e.code!=='ENOENT')throw e;}}return target;}
function checkName(name){nameSchema.parse(name);safeName(name);return name;}
function managed(root,name){return name.startsWith('isp-')||fs.existsSync(path.join(root,'templates/project/.agents/skills',name));}
function fileName(name){safeName(name);if(name.length>200||name.split('/').some(s=>s.startsWith('.'))||! /\.(md|txt|json|yaml|yml|py|js|mjs|cjs|ps1|sh|html|css|svg|csv)$/i.test(name))throw Error('Unsupported skill file: '+name);return name;}
function frontmatter(text,name){
 const match=text.replace(/\r\n/g,'\n').match(/^---\n([\s\S]*?)\n---(?:\n|$)/);if(!match)throw Error('SKILL.md needs YAML frontmatter with name and description');
 const field=key=>{const value=match[1].match(new RegExp('^'+key+':\\s*(.+)$','m'))?.[1]?.trim();if(value?.startsWith('"')){try{return JSON.parse(value);}catch{throw Error('Invalid quoted '+key);}}return value?.replace(/^'(.*)'$/,'$1');};
 if(field('name')!==name)throw Error('Frontmatter name must match folder name: '+name);
 let description=field('description');if(['|','>','|-','>-'].includes(description)){description=match[1].match(/^description:.*\n((?:[ \t]+.*(?:\n|$))+)/m)?.[1]?.trim().replace(/\s+/g,' ');}
 if(typeof description!=='string'||!description.trim()||description.length>2000)throw Error('A description including when to use this skill is required');return description;
}
function validateFiles(files,name){const keys=Object.keys(files);if(!keys.includes('SKILL.md')||keys.length>50)throw Error('Include SKILL.md; at most 50 files per skill');let total=0;const seen=new Set();for(const key of keys){fileName(key);if(seen.has(key.toLowerCase()))throw Error('Duplicate skill path');seen.add(key.toLowerCase());const text=files[key];if(typeof text!=='string'||text.includes('\0')||Buffer.byteLength(text)>256*1024)throw Error('Each skill file must be UTF-8 text, at most 256 KiB');total+=Buffer.byteLength(text);}if(total>2*1024*1024)throw Error('Skill exceeds 2 MiB');return frontmatter(files['SKILL.md'],name);}
function readFiles(w,prefix){const result={};let bytes=0;function visit(relative){const folder=safe(w,relative);for(const item of fs.readdirSync(folder,{withFileTypes:true})){const full=safe(w,relative+'/'+item.name);if(item.isDirectory())visit(relative+'/'+item.name);else if(item.isFile()){const key=(relative+'/'+item.name).slice(prefix.length+1);fileName(key);const size=fs.statSync(full).size;bytes+=size;if(size>256*1024||bytes>2*1024*1024||Object.keys(result).length>=50)throw Error('Skill size limit exceeded');const buffer=fs.readFileSync(full),text=buffer.toString('utf8');if(!Buffer.from(text).equals(buffer))throw Error('Only UTF-8 skill files are supported');result[key]=text;}}}visit(prefix);return result;}
const wrapper=(name,description)=>`---\nname: ${name}\ndescription: ${JSON.stringify(description)}\n---\n\nRead and follow [the project skill](../../../.agents/skills/${name}/SKILL.md). Resolve its supporting files relative to that canonical skill directory. This skill is local to this workspace.\n`;
export function readProjectSkill(w,root,name){checkName(name);const prefix='.agents/skills/'+name;const files=readFiles(w,prefix);const description=frontmatter(files['SKILL.md']||'',name);const canonical=Object.fromEntries(Object.entries(files).sort(([a],[b])=>a.localeCompare(b)));return {name,description,files,version:digest(JSON.stringify(canonical)),managed:managed(root,name)};}
export function listProjectSkills(w,root){const dir=safe(w,'.agents/skills');if(!fs.existsSync(dir))return [];return fs.readdirSync(dir,{withFileTypes:true}).filter(d=>d.isDirectory()||d.isSymbolicLink()).map(d=>{try{const skill=readProjectSkill(w,root,d.name);return {...skill,files:undefined,fileCount:Object.keys(skill.files).length};}catch(e){return {name:d.name,description:'',managed:managed(root,d.name),error:e.message};}}).sort((a,b)=>Number(a.managed)-Number(b.managed)||a.name.localeCompare(b.name));}
function plans(w,root,inputs){const names=new Set();return inputs.map(raw=>{const input=payloadSchema.parse(raw),name=checkName(input.name);if(managed(root,name))throw Error('Framework skills are read-only');if(names.has(name))throw Error('Duplicate skill');names.add(name);const description=validateFiles(input.files,name),dir=safe(w,'.agents/skills/'+name),bridge=safe(w,'.claude/skills/'+name),bridgeFile=safe(w,'.claude/skills/'+name+'/SKILL.md');const exists=fs.existsSync(dir),old=exists?readProjectSkill(w,root,name):null;if((old?.version||null)!==input.version)throw Error('Skill changed; refresh before replacing: '+name);
 if(fs.existsSync(bridge)){const entries=fs.readdirSync(bridge);const oldWrapper=old?wrapper(name,old.description):null;if(entries.length!==1||entries[0]!=='SKILL.md'||fs.readFileSync(bridgeFile,'utf8')!==oldWrapper)throw Error('Existing Claude skill differs; preserve it and resolve the name conflict: '+name);}
 return {...input,dir,bridge,description};});}
export function saveProjectSkills(w,root,inputs){if(!Array.isArray(inputs)||!inputs.length||inputs.length>100)throw Error('Choose 1–100 skills');const work=plans(w,root,inputs),base=safe(w,'.isp/skill-history/'+crypto.randomUUID());fs.mkdirSync(base,{recursive:true});const applied=[];
 try{for(const item of work){const stage=path.join(base,item.name+'-new'),bridgeStage=path.join(base,item.name+'-claude-new');fs.mkdirSync(stage);for(const [name,text]of Object.entries(item.files)){const target=path.join(stage,...name.split('/'));fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,text,{flag:'wx'});}fs.mkdirSync(bridgeStage);fs.writeFileSync(path.join(bridgeStage,'SKILL.md'),wrapper(item.name,item.description));
 const entry={...item,old:path.join(base,item.name+'-old'),oldBridge:path.join(base,item.name+'-claude-old'),moved:false,bridgeMoved:false};applied.push(entry);
 fs.mkdirSync(path.dirname(item.dir),{recursive:true});fs.mkdirSync(path.dirname(item.bridge),{recursive:true});if(fs.existsSync(item.dir))fs.renameSync(item.dir,entry.old);if(fs.existsSync(item.bridge))fs.renameSync(item.bridge,entry.oldBridge);fs.renameSync(stage,item.dir);entry.moved=true;fs.renameSync(bridgeStage,item.bridge);entry.bridgeMoved=true;
 }return work.map(p=>readProjectSkill(w,root,p.name));
 }catch(error){for(const p of applied.reverse()){if(p.moved)fs.renameSync(p.dir,path.join(base,p.name+'-failed'));if(p.bridgeMoved)fs.renameSync(p.bridge,path.join(base,p.name+'-claude-failed'));if(fs.existsSync(p.old))fs.renameSync(p.old,p.dir);if(fs.existsSync(p.oldBridge))fs.renameSync(p.oldBridge,p.bridge);}throw error;}
}
export function deleteProjectSkill(w,root,name,version){const item=readProjectSkill(w,root,name);plans(w,root,[{name,files:item.files,version}]);const base=safe(w,'.isp/skill-history/'+crypto.randomUUID());fs.mkdirSync(base,{recursive:true});const dir=safe(w,'.agents/skills/'+name),bridge=safe(w,'.claude/skills/'+name);fs.renameSync(dir,path.join(base,name));try{if(fs.existsSync(bridge))fs.renameSync(bridge,path.join(base,name+'-claude'));}catch(error){fs.renameSync(path.join(base,name),dir);throw error;}return {removed:name,backup:base};}
export async function exportSkillBundle(w,root,names,output){if(!Array.isArray(names)||!names.length||names.length>100||new Set(names).size!==names.length)throw Error('Choose distinct skills');const items=[],records=[];let total=0;for(const name of names){const s=readProjectSkill(w,root,name);if(s.managed)throw Error('Only project skills can be shared');validateFiles(s.files,name);records.push({name});for(const [file,text]of Object.entries(s.files)){const data=Buffer.from(text);total+=data.length;items.push({path:`skills/${name}/${file}`,data});}}if(total>MAX_TOTAL)throw Error('Skills bundle exceeds 10 MiB');await writeZip(output,[{path:'manifest.json',data:Buffer.from(JSON.stringify({format:'isp-project-skills',version:1,skills:records}))},...items]);}
export async function readSkillBundle(file){const zip=await openZip(file);try{if(zip.entries.length>5001||zip.entries.reduce((n,e)=>n+e.length,0)>MAX_TOTAL)throw Error('Skills bundle exceeds limits');const entry=zip.entries.find(e=>e.path==='manifest.json');if(!entry||entry.length>64000)throw Error('Not an ISP skills bundle');const manifest=z.object({format:z.literal('isp-project-skills'),version:z.literal(1),skills:z.array(z.object({name:nameSchema})).min(1).max(100)}).parse(JSON.parse((await zip.read(entry)).toString('utf8')));const map=new Map(manifest.skills.map(({name})=>[checkName(name),{}]));if(map.size!==manifest.skills.length)throw Error('Duplicate skills');for(const e of zip.entries){if(e===entry)continue;const [prefix,name,...parts]=e.path.split('/');if(prefix!=='skills'||!map.has(name)||e.length>256*1024)throw Error('Unexpected skills bundle file');const key=fileName(parts.join('/')),bytes=await zip.read(e),text=bytes.toString('utf8');if(!Buffer.from(text).equals(bytes))throw Error('Invalid UTF-8');map.get(name)[key]=text;}return [...map].map(([name,files])=>({name,description:validateFiles(files,name),files}));}finally{await zip.close();}}
export function installProjectSkills(app,{current,root}){
 const context=()=>current().workspace;
 app.get('/api/skills',(req,res)=>res.json(listProjectSkills(context(),root)));
 app.get('/api/skills/item/:name',(req,res)=>res.json(readProjectSkill(context(),root,req.params.name)));
 app.post('/api/skills/save',(req,res)=>res.json(saveProjectSkills(context(),root,[req.body])[0]));
 app.delete('/api/skills/item/:name',(req,res)=>res.json(deleteProjectSkill(context(),root,req.params.name,versionSchema.parse(req.body.version))));
 app.post('/api/skills/export',async(req,res,next)=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'isp-skills-'));try{const output=path.join(dir,'skills.bundle');await exportSkillBundle(context(),root,req.body.names,output);res.download(output,'project.skills.bundle',()=>fs.rmSync(dir,{recursive:true,force:true}));}catch(e){fs.rmSync(dir,{recursive:true,force:true});next(e);}});
 const upload=express.raw({type:'application/octet-stream',limit:'11mb'});
 const unpack=async(req,handler)=>{if(!Buffer.isBuffer(req.body))throw Error('Skills bundle binary required');const w=context(),dir=fs.mkdtempSync(path.join(os.tmpdir(),'isp-skills-import-'));try{const f=path.join(dir,'skills.bundle');fs.writeFileSync(f,req.body);const skills=await readSkillBundle(f);if(context()!==w)throw Error('Workspace changed');return handler(w,skills);}finally{fs.rmSync(dir,{recursive:true,force:true});}};
 app.post('/api/skills/import/preview',upload,async(req,res)=>res.json(await unpack(req,(w,skills)=>skills.map(s=>{if(managed(root,s.name))throw Error('Framework skill name is reserved');const existing=fs.existsSync(safe(w,'.agents/skills/'+s.name))?readProjectSkill(w,root,s.name):null;return {...s,version:existing?.version||null,conflict:!!existing};}))));
 app.post('/api/skills/import',upload,async(req,res)=>res.json(await unpack(req,(w,skills)=>{const choices=z.array(z.object({name:nameSchema,version:versionSchema})).min(1).max(100).parse(JSON.parse(decodeURIComponent(req.headers['x-skill-choices']||'[]')));return saveProjectSkills(w,root,choices.map(choice=>{const s=skills.find(s=>s.name===choice.name);if(!s)throw Error('Skill not in bundle');return {...s,...choice};}));})));
}
