import {useState} from 'react';
import {FolderOpen,X} from 'lucide-react';
import {WorkspacePicker} from './WorkspacePicker';
import type {Api} from './types';
type Restored={id:string;workspace:string;name:string;includeImages:boolean};
export function BundleOpen({api,token,current,dirty}:{api:Api;token:string;current:string;dirty:boolean}){
 const [open,setOpen]=useState(false),[file,setFile]=useState<File|null>(null),[destination,setDestination]=useState(''),[picker,setPicker]=useState(false),[busy,setBusy]=useState(false),[phase,setPhase]=useState(''),[error,setError]=useState(''),[restored,setRestored]=useState<Restored|null>(null);
 const folderName=()=>file?.name.replace(/\.bundle$/i,'').replace(/[<>:"/\\|?*]/g,'_')||'imported-project';
 async function restore(){if(busy||dirty)return;setBusy(true);setError('');try{let result=restored;if(!result){if(!file)throw new Error('번들 파일을 선택하세요.');setPhase('업로드 · 검증 · 복원 중…');const response=await fetch('/api/bundle/import',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/octet-stream','X-Bundle-Destination':encodeURIComponent(destination)},body:file});if(!response.ok)throw new Error((await response.json()).error||'번들 복원 실패');result=await response.json() as Restored;setRestored(result);}setPhase('복원된 프로젝트 서버 시작 중…');const {url}=await api<{url:string}>('/bundle/open',{id:result.id});const target=new URL(url);if(target.protocol!=='http:'||target.hostname!=='127.0.0.1')throw new Error('잘못된 로컬 서버 주소');location.assign(target.href);}catch(e){setError(String(e));}finally{setBusy(false);setPhase('');}}
 return <><button className="bundle-share-button" aria-label="번들 열기" title=".bundle 파일에서 프로젝트 복원" onClick={()=>{setDestination(current+'-import');setFile(null);setRestored(null);setError('');setOpen(true);}}><FolderOpen size={15}/><span>번들 열기</span></button>{open&&<div className="workspace-picker-backdrop"><section className="bundle-dialog" role="dialog" aria-modal="true" aria-label="번들 열기" onKeyDown={e=>{if(e.key==='Escape'&&!busy&&!picker)setOpen(false);}}><header><div><h2>번들 열기</h2><p>새 폴더에 복원하고 해당 프로젝트 화면으로 이동합니다.</p></div><button autoFocus disabled={busy} aria-label="번들 열기 닫기" onClick={()=>setOpen(false)}><X size={18}/></button></header><label className="bundle-field">번들 파일<input aria-label="번들 파일" type="file" accept=".bundle" disabled={busy||!!restored} onChange={e=>{setFile(e.target.files?.[0]||null);setError('');}}/></label><label className="bundle-field">복원할 새 폴더<input aria-label="복원할 새 폴더" value={destination} disabled={busy||!!restored} onChange={e=>setDestination(e.target.value)}/></label><button disabled={busy||!!restored} onClick={()=>setPicker(true)}>부모 폴더 찾아보기</button><p>부모 폴더는 존재해야 하며 마지막 폴더 이름은 새 이름이어야 합니다. 기존 파일을 덮어쓰지 않습니다. 현재 프로젝트 서버는 유지됩니다.</p>{dirty&&<p role="alert">현재 작성 중인 변경을 저장한 뒤 번들을 여세요.</p>}{restored&&<p role="status">복원 완료: {restored.workspace}<br/>서버 열기에 실패해도 복원된 파일은 유지됩니다.</p>}{error&&<p role="alert">{error}</p>}<footer><p>{restored?<code>isp-block-maker "{restored.workspace}"</code>:'번들에 포함되지 않은 Python 패키지나 외부 데이터는 별도로 준비하세요.'}</p><button className="primary" disabled={busy||dirty||(!restored&&(!file||!destination))} onClick={()=>void restore()}>{busy?phase:restored?'프로젝트 열기 다시 시도':'복원하고 열기'}</button></footer></section></div>}{picker&&<WorkspacePicker api={api} current={current} onClose={()=>setPicker(false)} onPick={parent=>{setDestination(parent.replace(/[\\/]$/,'')+'/'+folderName());setPicker(false);}}/>}</>;
}
