import {useEffect,useState} from 'react';
import {Package,Download,X} from 'lucide-react';
import type {Api} from './types';
type Plan={fileCount:number;bytes:number;revision:number;skipped:string[];files:{path:string;size:number}[];includeGit:boolean};
const size=(bytes:number)=>bytes<1024*1024?`${(bytes/1024).toFixed(1)} KiB`:`${(bytes/1024/1024).toFixed(1)} MiB`;
export function BundleShare({api,token,dirty}:{api:Api;token:string;dirty:boolean}){
 const [open,setOpen]=useState(false),[images,setImages]=useState(true),[git,setGit]=useState(false),[plan,setPlan]=useState<Plan|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[refresh,setRefresh]=useState(0),[notice,setNotice]=useState('');
 useEffect(()=>{if(!open)return;let alive=true;setPlan(null);setError('');api<Plan>(`/bundle/preview?includeImages=${images}&includeGit=${git}`).then(p=>{if(alive)setPlan(p);}).catch(e=>{if(alive)setError(String(e));});return()=>{alive=false;};},[api,open,images,git,refresh]);
 async function download(){if(!plan||busy||dirty)return;setBusy(true);setError('');setNotice('');try{const res=await fetch('/api/bundle/export',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({includeImages:images,includeGit:git,revision:plan.revision})});if(!res.ok)throw new Error((await res.json()).error||'Bundle export failed');const blob=await res.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='workspace.bundle';a.click();setNotice('번들 다운로드를 시작했습니다.');setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError(String(e));}finally{setBusy(false);}}
 return <><button className="bundle-share-button" title="프로젝트를 .bundle로 공유" aria-label="프로젝트 공유" onClick={()=>setOpen(true)}><Package size={15}/><span>공유</span></button>{open&&<div className="workspace-picker-backdrop"><section className="bundle-dialog" role="dialog" aria-modal="true" aria-label="프로젝트 번들 저장" onKeyDown={e=>{if(e.key==='Escape'&&!busy)setOpen(false);}}><header><div><h2>프로젝트 공유</h2><p>그래프, 코드, 요청/JOB, 시각화와 크롭을 .bundle 하나로.</p></div><button autoFocus disabled={busy} aria-label="번들 창 닫기" onClick={()=>setOpen(false)}><X size={18}/></button></header><label className="bundle-option"><input type="checkbox" checked={images} disabled={busy} onChange={e=>setImages(e.target.checked)}/><span>Viewer 원본 이미지 포함 <small>기본 포함. 끄면 기존 크롭은 보존되지만 원본 미리보기·새 크롭은 사용할 수 없습니다.</small></span></label><label className="bundle-option"><input type="checkbox" checked={git} disabled={busy} onChange={e=>setGit(e.target.checked)}/><span>Git 이력 포함 <small>독립 프로젝트 저장소만 지원합니다. 과거 커밋 내용도 함께 전달됩니다.</small></span></label><p className="bundle-hint">에이전트의 파일 수정을 잠시 멈추고 설명·요청을 저장하세요. 접속정보, 개인 설정, 가상환경은 제외합니다. 파일 안에 직접 적은 비밀값은 검사하지 않으므로 포함 목록을 확인하세요.</p>{dirty&&<p role="alert">작성 중인 블록 변경을 저장한 뒤 번들을 내려받으세요.</p>}{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}{plan?<><div className="bundle-size"><strong>{plan.fileCount.toLocaleString()}개 파일 · {size(plan.bytes)}</strong><small>ZIP 저장 방식 · 헤더{git?' 및 Git 이력':''} 용량 별도 · 최대 2 GiB / 파일당 256 MiB</small><button disabled={busy} onClick={()=>setRefresh(n=>n+1)}>목록 새로고침</button></div><details><summary>포함 파일</summary><ul className="bundle-files">{plan.files.map(f=><li key={f.path}><code>{f.path}</code><span>{size(f.size)}</span></li>)}</ul></details><details><summary>제외 항목 ({plan.skipped.length})</summary><ul className="bundle-files">{plan.skipped.map(f=><li key={f}><code>{f}</code></li>)}</ul></details></>:!error&&<p role="status">포함 파일과 용량 확인 중…</p>}<footer><p>받는 사람은 새 폴더로 복원합니다.<code>isp-block-maker open workspace.bundle --into C:\Work\MyISP</code></p><button className="primary" disabled={!plan||busy||dirty} onClick={()=>void download()}><Download size={16}/>{busy?'번들 만드는 중…':'.bundle 저장'}</button></footer></section></div>}</>;
}
