import {useEffect,useRef,useState} from 'react';
import type {Api,Project} from './types';
import {builtin,renderGpu,synthetic,type GpuExtension,type GpuSync} from './gpu';
export function GpuSimulator({api,project,dirty,onSaved}:{api:Api;project:Project;dirty:boolean;onSaved:(id:string)=>void}){
 const [extensions,setExtensions]=useState<GpuExtension[]>([builtin]),[extensionId,setExtensionId]=useState(builtin.id),[values,setValues]=useState<Record<string,number>>({}),[input,setInput]=useState<HTMLCanvasElement|null>(null),[inputName,setInputName]=useState('Synthetic · seed 12345'),[error,setError]=useState(''),[catalogError,setCatalogError]=useState(''),[stats,setStats]=useState(''),[busy,setBusy]=useState(false),[baseline,setBaseline]=useState(''),[baselineLabel,setBaselineLabel]=useState(''),[saving,setSaving]=useState(false);
 const [syncStatuses,setSyncStatuses]=useState<Record<string,GpuSync>>({});
 const output=useRef<HTMLCanvasElement>(null),imageLoad=useRef(0),rendered=useRef(false);
 const extension=extensions.find(e=>e.id===extensionId)||builtin;
 async function reload(){try{const r=await api<{extensions:GpuExtension[];errors:{file:string;error:string}[]}>('/gpu/extensions');setExtensions(previous=>[builtin,...r.extensions.map(e=>previous.find(old=>old.id===e.id&&old.hash===e.hash)||e)]);setSyncStatuses(Object.fromEntries(r.extensions.filter(e=>e.sync).map(e=>[e.id,e.sync!])));setCatalogError(r.errors.map(e=>`${e.file}: ${e.error}`).join('\n'));}catch(e){setCatalogError(String(e));}}
 useEffect(()=>{const c=output.current;const lost=(e:Event)=>{e.preventDefault();rendered.current=false;setError("GPU context 손실. 다른 탭으로 이동한 뒤 다시 여세요.");};c?.addEventListener("webglcontextlost",lost);return()=>c?.removeEventListener("webglcontextlost",lost);},[]);
 useEffect(()=>{void reload();setInput(synthetic());return()=>{++imageLoad.current;};},[api]);
 useEffect(()=>{const timer=setInterval(()=>{if(document.visibilityState==='visible')void reload();},15000);return()=>clearInterval(timer);},[api]);
 const sync=syncStatuses[extension.id];
 useEffect(()=>{setValues(Object.fromEntries(extension.parameters.map(p=>{const value=p.blockId&&p.parameter?project.blocks.find(b=>b.id===p.blockId)?.parameters[p.parameter]:p.default;return [p.name,typeof value==='number'?Math.max(p.min,Math.min(p.max,value)):p.default];})));setBaseline('');},[extension]);
 useEffect(()=>{if(!input||!output.current)return;rendered.current=false;setBusy(true);const frame=requestAnimationFrame(()=>{try{const start=performance.now(),pixels=renderGpu(output.current!,input,extension,values),src=input.getContext('2d')!.getImageData(0,0,input.width,input.height).data;let sum=0;for(let y=0;y<input.height;y++)for(let x=0;x<input.width;x++)for(let c=0;c<3;c++){const a=((input.height-1-y)*input.width+x)*4+c,b=(y*input.width+x)*4+c;sum+=(pixels[a]-src[b])**2;}setStats(`입력 대비 RMSE ${(Math.sqrt(sum/(input.width*input.height*3))/255).toFixed(6)} · 처리+읽기 ${(performance.now()-start).toFixed(1)} ms`);setError('');rendered.current=true;}catch(e){setError(String(e));setStats('');}finally{setBusy(false);}});return()=>cancelAnimationFrame(frame);},[input,extension,values]);
 async function upload(file?:File){if(!file)return;const id=++imageLoad.current;setError('');try{if(file.size>20*1024*1024)throw new Error('20MB 이하의 이미지를 선택하세요.');const bitmap=await createImageBitmap(file);if(id!==imageLoad.current){bitmap.close();return;}const c=document.createElement('canvas'),scale=Math.min(1,1024/Math.max(bitmap.width,bitmap.height));c.width=Math.max(1,Math.round(bitmap.width*scale));c.height=Math.max(1,Math.round(bitmap.height*scale));c.getContext('2d')!.drawImage(bitmap,0,0,c.width,c.height);bitmap.close();setInput(c);setInputName(`${file.name} · ${c.width}×${c.height}`);setBaseline('');}catch(e){if(id===imageLoad.current)setError(String(e));}}
 const sha256=async(bytes:Uint8Array)=>Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",new Uint8Array(bytes).buffer))).map(v=>v.toString(16).padStart(2,"0")).join("");
 async function save(){if(!rendered.current||!output.current)return;setSaving(true);try{const result=await api<{id:string}>('/artifacts',{title:`GPU · ${extension.name}`,blockId:extension.blockId||project.selectedBlockId||project.blocks[0].id,revision:project.revision,kind:'png',content:output.current.toDataURL('image/png').split(',')[1],metadata:{syncStatus:catalogError?'unavailable':sync?.status||'unrecorded',engine:'WebGL2',extension:extension.id,extensionHash:extension.hash,shaderHash:await sha256(new TextEncoder().encode(extension.fragment)),inputSha256:await sha256(new Uint8Array(input!.getContext('2d')!.getImageData(0,0,input!.width,input!.height).data)),parameters:values,input:inputName,width:input?.width,height:input?.height,precision:'RGBA8 preview; not CPU equivalence',...(await api<{head?:{hash:string};dirty?:boolean}>('/versions').then(v=>({commit:v.head?.hash,dirty:v.dirty})))}});onSaved(result.id);}catch(e){setError(String(e));}finally{setSaving(false);}}
 async function apply(){if(dirty){setError("작성 중인 블록 변경을 먼저 저장하거나 취소하세요.");return;}setSaving(true);try{const next=structuredClone(project);for(const p of extension.parameters){if(!p.blockId||!p.parameter)continue;const block=next.blocks.find(b=>b.id===p.blockId);if(!block||!(p.parameter in block.parameters))throw new Error(`연결된 파라미터가 없습니다: ${p.blockId}.${p.parameter}`);block.parameters[p.parameter]=values[p.name]??p.default;}await api('/project',next,'PUT');setError('');}catch(e){setError(String(e));}finally{setSaving(false);}}
 return <section className="work-board gpu-simulator"><header><h1>GPU simulator</h1><p>프로젝트 GPU 확장으로 파라미터를 즉시 비교합니다. 슬라이더는 미리보기 값입니다.</p></header><div className="work-controls"><select aria-label="GPU extension" value={extension.id} onChange={e=>setExtensionId(e.target.value)}>{extensions.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select><button onClick={()=>void reload()}>확장 새로고침</button><label>이미지 열기<input aria-label="GPU 입력 이미지" type="file" accept="image/*" onChange={e=>void upload(e.target.files?.[0])}/></label><button onClick={()=>{++imageLoad.current;setInput(synthetic());setInputName('Synthetic · seed 12345');setBaseline('');}}>합성 입력</button></div><p>{extension.description}</p>{extension.id!==builtin.id&&<div className="gpu-sync" role="status"><strong>{catalogError?'동기화 상태 조회 실패':sync?.status==='match'?'기준 소스 · 셰이더 해시 일치':sync?.status==='changed'?'동기화 확인 필요':sync?.status==='unavailable'?'기준 소스 확인 불가':'동기화 기준 미등록'}</strong>{!catalogError&&sync?.details.map((line,i)=><p key={i}>{line}</p>)}<small>기록한 파일의 변경 여부입니다. 알고리즘 동등성이나 GPU 검증 통과를 의미하지 않습니다.</small></div>}<details><summary>확장 연결 방법</summary><p>프로젝트의 extensions/gpu/*.json에 version:1, id, name, description, fragment(GLSL ES 3.00), parameters를 정의하세요. u_image는 RGBA8 입력, u_resolution은 크기입니다. 수치 uniform은 float입니다. 블록 대응은 blockId와 parameter로 명시합니다. Python 자동 변환이나 RAW 정밀도 검증은 수행하지 않습니다.</p></details>
 {catalogError&&<pre role="alert">{catalogError}</pre>}{error&&<pre role="alert">{error}</pre>}
 <div className="gpu-sliders">{extension.parameters.map(p=><label key={p.name}>{p.label} <output>{values[p.name]??p.default}</output><input aria-label={p.label} type="range" min={p.min} max={p.max} step={p.step} value={values[p.name]??p.default} onChange={e=>setValues(v=>({...v,[p.name]:Number(e.target.value)}))}/></label>)}</div>
 <div className="gpu-images"><figure><figcaption>입력 · {inputName}</figcaption>{input&&<img src={input.toDataURL()} alt="GPU 입력"/>}</figure><figure><figcaption>GPU 출력 · {busy?'처리 중':stats}</figcaption><canvas ref={output} aria-label="GPU 출력"/></figure>{baseline&&<figure><figcaption>고정 비교 · {baselineLabel}</figcaption><img src={baseline} alt="고정한 GPU 결과"/></figure>}</div>
 <div className="work-controls"><button disabled={busy||!!error||!input} onClick={()=>{if(rendered.current){setBaseline(output.current!.toDataURL());setBaselineLabel(JSON.stringify(values));}}}>현재 결과 고정</button><button onClick={()=>setValues(Object.fromEntries(extension.parameters.map(p=>[p.name,p.default])))}>기본값 복원</button><button disabled={dirty||saving||busy||!!error||!extension.parameters.some(p=>p.blockId&&p.parameter)} onClick={()=>void apply()}>그래프에 파라미터 적용</button><button disabled={saving||busy||!!error||!input} onClick={()=>void save()}>시각화에 결과 저장</button></div><small>RGBA8 · 입력 최대 1024px · RMSE는 입력과의 차이이며 품질 점수가 아닙니다. 처리 시간은 GPU 단독 시간이 아닙니다.</small></section>;
}
