import {useEffect,useState} from 'react';
import {BookOpen,Plus,Download,Upload,RefreshCw,Save,Trash2,Search,ShieldCheck,Sparkles,FileCode2} from 'lucide-react';
import type {Api} from './types';
import './project-skills.css';
type Skill={name:string;description:string;managed:boolean;version:string|null;files:Record<string,string>;error?:string;fileCount?:number};
type Incoming=Skill&{conflict:boolean};
const example=(name:string)=>`---\nname: ${name}\ndescription: "이 프로젝트에서 어떤 작업에 사용하는지 적으세요."\n---\n\n# 작업 절차\n\n프로젝트에 특화된 규칙, 검증 방법, 참조 경로를 적으세요.\n`;
export function ProjectSkills({api,token}:{api:Api;token:string}){
 const [catalog,setCatalog]=useState<Skill[]>([]),[selected,setSelected]=useState<Skill|null>(null),[name,setName]=useState(''),[files,setFiles]=useState<Record<string,string>>({}),[file,setFile]=useState('SKILL.md'),[newFile,setNewFile]=useState(''),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [search,setSearch]=useState('');
 const [exportNames,setExportNames]=useState<string[]>([]),[bundle,setBundle]=useState<File|null>(null),[incoming,setIncoming]=useState<Incoming[]>([]),[chosen,setChosen]=useState<string[]>([]);
 async function refresh(){setCatalog(await api<Skill[]>('/skills'));}
 useEffect(()=>{void refresh().catch(e=>setError(String(e)));},[api]);
 useEffect(()=>{if(!dirty)return;const before=(e:BeforeUnloadEvent)=>{e.preventDefault();};window.addEventListener('beforeunload',before);return()=>window.removeEventListener('beforeunload',before);},[dirty]);
 const discard=()=>!dirty||confirm('저장하지 않은 스킬 편집을 버릴까요?');
 async function run(action:()=>Promise<void>){if(busy)return;setBusy(true);setError('');setNotice('');try{await action();}catch(e){setError(String(e));}finally{setBusy(false);}}
 function load(s:Skill){setSelected(s);setName(s.name);setFiles(s.files);setFile('SKILL.md');setDirty(false);}
 async function save(){await run(async()=>{const s=await api<Skill>('/skills/save',{name,files,version:selected?.version||null});load(s);await refresh();setNotice('프로젝트 스킬과 Claude 진입점을 저장했습니다. 실행 중인 에이전트는 스킬 목록을 다시 확인하세요.');});}
 async function binary(route:string,init:RequestInit){const r=await fetch('/api/skills/'+route,{...init,headers:{Authorization:`Bearer ${token}`,...init.headers}});if(!r.ok)throw Error((await r.json()).error||'스킬 처리 실패');return r;}
 async function preview(f:File){await run(async()=>{if(f.size>11*1024*1024)throw Error('스킬 번들은 최대 11 MiB입니다.');const r=await binary('import/preview',{method:'POST',headers:{'Content-Type':'application/octet-stream'},body:f});const list=await r.json() as Incoming[];setBundle(f);setIncoming(list);setChosen(list.filter(s=>!s.conflict).map(s=>s.name));});}
 return <section className="work-board project-skills" onKeyDown={e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();e.stopPropagation();if(dirty&&!busy&&!selected?.managed)void save();}}}><header className="skills-heading"><div className="skills-emblem"><BookOpen size={23}/></div><div><span className="skills-eyebrow">WORKSPACE KNOWLEDGE</span><h1>Project Skills</h1><p>반복되는 노하우를 에이전트가 다시 쓸 수 있는 작업 절차로.</p></div><span className="skills-count">{catalog.filter(s=>!s.managed).length} project skills</span></header>
 <div className="skill-actions"><button disabled={busy} onClick={()=>{if(discard()){const n='project-skill';setSelected(null);setName(n);setFiles({'SKILL.md':example(n)});setFile('SKILL.md');setDirty(true);}}}><Plus size={15}/> 새 스킬</button><button disabled={busy} aria-label="스킬 목록 새로고침" onClick={()=>void run(refresh)}><RefreshCw size={15}/></button><button disabled={busy||!exportNames.length} onClick={()=>void run(async()=>{const r=await binary('export',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({names:exportNames})});const url=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=url;a.download='project.skills.bundle';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);})}><Download size={15}/> 선택 스킬 공유 ({exportNames.length})</button><label className="skill-upload"><Upload size={15}/> 스킬 번들 열기<input aria-label="스킬 번들 파일" disabled={busy} type="file" accept=".bundle" onChange={e=>{const f=e.target.files?.[0];e.target.value='';if(f){setIncoming([]);setBundle(null);void preview(f);}}}/></label></div>
 {error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 {incoming.length>0&&<section className="skill-import"><h2>가져오기 미리보기</h2><p>선택한 스킬은 에이전트가 읽을 수 있게 설치됩니다. 내용과 스크립트를 확인하세요. 가져오는 동안 스크립트를 실행하지 않습니다. 같은 이름은 명시적으로 선택해야 덮어씁니다.</p>{incoming.map(s=><details key={s.name}><summary><input aria-label={`${s.name} 가져오기`} type="checkbox" checked={chosen.includes(s.name)} onClick={e=>e.stopPropagation()} onChange={e=>setChosen(old=>e.target.checked?[...old,s.name]:old.filter(n=>n!==s.name))}/>{s.name} · {s.conflict?'기존 스킬 덮어쓰기':'새 스킬'}</summary><p>{s.description}</p>{Object.entries(s.files).map(([key,text])=><details key={key}><summary>{key}</summary><pre>{text}</pre></details>)}</details>)}<button disabled={busy||!chosen.length} onClick={()=>{if(!discard())return;void run(async()=>{await binary('import',{method:'POST',headers:{'Content-Type':'application/octet-stream','X-Skill-Choices':encodeURIComponent(JSON.stringify(incoming.filter(s=>chosen.includes(s.name)).map(s=>({name:s.name,version:s.version}))))},body:bundle});setIncoming([]);setBundle(null);setSelected(null);setName('');setFiles({});setDirty(false);await refresh();setNotice('선택한 프로젝트 스킬을 가져왔습니다.');});}}>선택 항목 가져오기</button><button disabled={busy} onClick={()=>{setIncoming([]);setBundle(null);}}>닫기</button></section>}
 <div className="skill-columns"><nav aria-label="프로젝트 스킬 목록"><label className="skills-search"><Search size={15}/><input aria-label="스킬 검색" placeholder="스킬 검색" value={search} onChange={e=>setSearch(e.target.value)}/></label><div className="skills-list-caption">SKILL LIBRARY <span>{catalog.length}</span></div>{catalog.filter(s=>(s.name+" "+s.description).toLowerCase().includes(search.toLowerCase())).map(s=><div className="skill-list-row" key={s.name}>{!s.managed&&!s.error&&<input aria-label={`${s.name} 공유 선택`} type="checkbox" checked={exportNames.includes(s.name)} onChange={e=>setExportNames(old=>e.target.checked?[...old,s.name]:old.filter(n=>n!==s.name))}/>}<button disabled={busy||!!s.error} aria-pressed={selected?.name===s.name} onClick={()=>{if(discard())void run(async()=>load(await api<Skill>('/skills/item/'+encodeURIComponent(s.name))));}}><span className="skill-card-title">{s.managed?<ShieldCheck size={15}/>:<Sparkles size={15}/>}<strong>{s.name}</strong></span><small>{s.managed?'프레임워크 기본 · 읽기 전용':'프로젝트'} · {s.error||s.description}</small></button></div>)}{!catalog.some(s=>!s.managed)&&<p>반복되는 프로젝트 규칙을 발견하면 새 스킬로 정리하세요.</p>}</nav>
 <div className="skill-editor">{name?<><div className="skills-editor-heading"><span><FileCode2 size={16}/> {selected?.managed?"기본 스킬":"프로젝트 스킬"}</span><span className={`skill-badge ${dirty?"unsaved":""}`}>{selected?.managed?"READ ONLY":dirty?"UNSAVED":"SAVED"}</span></div><label>스킬 이름<input aria-label="스킬 이름" disabled={!!selected||busy} value={name} onChange={e=>{const next=e.target.value;setName(next);setFiles(old=>({...old,'SKILL.md':old['SKILL.md'].replace(/^name: .*$/m,'name: '+next)}));setDirty(true);}}/></label><p>{selected?.managed?'설치된 기본 스킬입니다. 프로젝트 지식은 새 스킬에 작성하세요.':'name과 description으로 사용 시점을 설명하고 상세 절차는 본문·참조 파일에 적으세요.'}</p><select aria-label="스킬 파일 선택" value={file} onChange={e=>setFile(e.target.value)}>{Object.keys(files).map(key=><option key={key}>{key}</option>)}</select><textarea className="skill-source" aria-label="스킬 파일 내용" readOnly={selected?.managed||busy} value={files[file]||''} spellCheck={false} onChange={e=>{setFiles(old=>({...old,[file]:e.target.value}));setDirty(true);}}/>
 {!selected?.managed&&<><div className="skill-actions"><input aria-label="새 스킬 파일 경로" placeholder="references/raw-layout.md" value={newFile} onChange={e=>setNewFile(e.target.value)}/><button disabled={busy||!newFile.trim()||newFile.trim() in files} onClick={()=>{const key=newFile.trim();if(!key||key in files)return;setFiles(old=>({...old,[key]:''}));setFile(key);setNewFile('');setDirty(true);}}>파일 추가</button>{file!=='SKILL.md'&&<button disabled={busy} onClick={()=>{setFiles(old=>Object.fromEntries(Object.entries(old).filter(([key])=>key!==file)));setFile('SKILL.md');setDirty(true);}}>파일 제거</button>}</div><div className="skill-actions"><button disabled={busy||!dirty} onClick={()=>void save()}><Save size={15}/> 저장</button>{selected&&<button disabled={busy} onClick={()=>{if(confirm('프로젝트 스킬을 삭제할까요? 기존 파일은 .isp/skill-history에 보관합니다.'))void run(async()=>{const r=await api<{backup:string}>('/skills/item/'+encodeURIComponent(selected.name),{version:selected.version},'DELETE');setExportNames(old=>old.filter(n=>n!==selected.name));setSelected(null);setName('');setFiles({});setDirty(false);await refresh();setNotice('삭제한 스킬 백업: '+r.backup);});}}><Trash2 size={15}/> 삭제</button>}<small>{dirty?'저장 전 변경사항 있음':'저장됨'}</small></div></>}
 </>:<div className="skills-empty"><div className="skills-emblem"><Sparkles size={28}/></div><h2>프로젝트의 노하우를 쌓아보세요</h2><p>왼쪽에서 스킬을 선택하거나 새 스킬을 만드세요.</p><div className="skills-examples"><span>RAW 해석 규칙</span><span>블록 검증 절차</span><span>C-model 이식 요령</span></div><small>필요한 스킬만 공유하거나 프로젝트 번들에 함께 담을 수 있습니다.</small></div>}</div></div>{busy&&<p role="status">처리 중…</p>}</section>;
}
