import {useEffect,useState} from 'react';
import {Download,Plus,Trash2,RefreshCw} from 'lucide-react';
import type {Api,Project} from './types';
import './reference-sets.css';

type Entry={id:string;name:string;role:string;description:string;metadata:Record<string,unknown>;size:number;sha256:string};
type SetRecord={id:string;title:string;description:string;blockIds:string[];checkpointId:string|null;createdAt:string;updatedAt:string;metadata:Record<string,unknown>;provenance:{gitHead:string|null;dirty:boolean|null;note:string};files:Entry[]};
type Comparison={equal:boolean;differentBytes:number;expectedBytes:number;actualBytes:number;firstDifferences:{offset:number;expected:number;actual:number}[]};
export function ReferenceSets({api,token,project}:{api:Api;token:string;project:Project}){
 const [sets,setSets]=useState<SetRecord[]>([]),[selected,setSelected]=useState(''),[creating,setCreating]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [title,setTitle]=useState(''),[description,setDescription]=useState(''),[blocks,setBlocks]=useState<string[]>([]),[checkpoint,setCheckpoint]=useState(''),[spec,setSpec]=useState('{}'),[paths,setPaths]=useState('');
 const [role,setRole]=useState('input'),[fileDescription,setFileDescription]=useState(''),[fileSpec,setFileSpec]=useState('{}'),[expected,setExpected]=useState(''),[actual,setActual]=useState(''),[comparison,setComparison]=useState<Comparison|null>(null);
 const current=sets.find(s=>s.id===selected);
 async function refresh(){const next=await api<SetRecord[]>('/reference-sets');setSets(next);}
 useEffect(()=>{void refresh().catch(e=>setError(String(e)));},[api]);
 useEffect(()=>{setExpected('');setActual('');setComparison(null);},[selected]);
 async function run(action:()=>Promise<void>){if(busy)return;setBusy(true);setError('');try{await action();}catch(e){setError(String(e));}finally{setBusy(false);}}
 function json(text:string){const value=JSON.parse(text||'{}');if(!value||Array.isArray(value)||typeof value!=='object')throw new Error('규격은 JSON 객체로 입력하세요.');return value;}
 async function create(crops=false){await run(async()=>{let cropDeliveryId:string|undefined;if(crops){const delivery=await api<{id:string;missing:unknown[]}|null>('/viewer/crop-selection');if(!delivery||delivery.missing?.length)throw new Error('Viewer에서 크롭을 선택해 전달한 뒤 다시 시도하세요.');cropDeliveryId=delivery.id;}
  const value=await api<SetRecord>('/reference-sets',{title,description,blockIds:blocks,checkpointId:checkpoint.trim()||null,metadata:json(spec),files:paths.split(/\r?\n/).map(p=>p.trim()).filter(Boolean).map(p=>({path:p,name:p.split(/[\\/]/).pop(),role,metadata:json(fileSpec),description:fileDescription})),...(cropDeliveryId?{cropDeliveryId}:{})});await refresh();setSelected(value.id);setCreating(false);setTitle('');setDescription('');setPaths('');
 });}
 async function upload(files:File[]){if(!current)return;const id=current.id;await run(async()=>{try{const metadata=json(fileSpec);for(const file of files){if(file.size>256*1024*1024)throw new Error(`${file.name}: 파일 한도는 256 MiB입니다.`);const response=await fetch(`/api/reference-sets/${id}/files`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/octet-stream','X-Reference-Metadata':encodeURIComponent(JSON.stringify({name:file.name,role,description:fileDescription,metadata}))},body:file});const value=await response.json();if(!response.ok)throw new Error(`${file.name}: ${value.error}`);}}finally{await refresh();}});}
 async function download(route:string,name:string){await run(async()=>{const response=await fetch('/api'+route,{headers:{Authorization:`Bearer ${token}`}});if(!response.ok)throw new Error((await response.json()).error);const url=URL.createObjectURL(await response.blob()),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});}
 return <section className="work-board reference-sets"><header><h1>Reference I/O</h1><p>필요한 지점의 입력·출력을 보관합니다. 블록 연결과 파일 규격은 선택 사항이며 구현끼리 1:1 대응하지 않아도 됩니다.</p></header>
 <div className="work-controls"><button disabled={busy} onClick={()=>setCreating(v=>!v)}><Plus size={15}/> 참조 세트 만들기</button><button disabled={busy} aria-label="참조 세트 새로고침" onClick={()=>void run(refresh)}><RefreshCw size={15}/></button><select aria-label="참조 세트 선택" disabled={busy} value={selected} onChange={e=>setSelected(e.target.value)}><option value="">세트 선택</option>{sets.map(s=><option key={s.id} value={s.id}>{s.title} · {s.files.length} files</option>)}</select></div>
 {error&&<p role="alert">{error}</p>}
 {creating&&<form onSubmit={e=>{e.preventDefault();void create();}}><fieldset disabled={busy}><legend>새 참조 입출력 세트</legend><label>이름<input required value={title} onChange={e=>setTitle(e.target.value)} maxLength={200}/></label><label>설명 · 구간 · 실행 조건<textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="예: flat 앞의 입력과 threshold 뒤의 출력. C-model 함수 하나와 비교."/></label><details><summary>블록 연결 · 규격 · 체크포인트 (선택)</summary><div className="reference-blocks">{project.blocks.map(b=><label key={b.id}><input type="checkbox" checked={blocks.includes(b.id)} onChange={e=>setBlocks(old=>e.target.checked?[...old,b.id]:old.filter(id=>id!==b.id))}/>{b.name}</label>)}</div><label>체크포인트 ID<input value={checkpoint} onChange={e=>setCheckpoint(e.target.value)} placeholder="이 파일을 생성한 구현의 체크포인트 · 생략 가능"/></label><label>자유 메타데이터 JSON<textarea value={spec} onChange={e=>setSpec(e.target.value)} spellCheck={false}/></label></details><details><summary>Workspace 파일 경로로 등록 (선택)</summary><p>경로당 한 줄. 현재 아래에서 선택한 파일 역할·규격을 사용합니다. 원본을 보존하고 사본을 저장합니다.</p><textarea aria-label="참조 파일 경로" value={paths} onChange={e=>setPaths(e.target.value)} placeholder={'tmp/run/input.raw\ntmp/run/output.raw'}/></details><div className="work-controls"><button type="submit" disabled={!title.trim()}>만들기</button><button type="button" disabled={!title.trim()} onClick={()=>void create(true)}>최근 전달 크롭으로 만들기</button></div><small>크롭 가져오기는 전달을 소비하지 않습니다. 파일은 생성 후에도 추가할 수 있습니다.</small></fieldset></form>}
 {(creating||current)&&<fieldset disabled={busy}><legend>추가할 파일의 역할·규격</legend><label>역할<select aria-label="참조 파일 역할" value={role} onChange={e=>setRole(e.target.value)}><option value="input">입력</option><option value="output">출력</option><option value="other">기타</option></select></label><label>파일 설명<input value={fileDescription} onChange={e=>setFileDescription(e.target.value)} placeholder="Python 결과 / C-model 결과 / 중간 덤프 등 자유롭게"/></label><label>규격 JSON (선택)<textarea aria-label="참조 파일 규격" value={fileSpec} onChange={e=>setFileSpec(e.target.value)} placeholder={'{"dtype":"uint16","shape":[1080,1920],"pattern":"GRBG","bitDepth":12,"byteOrder":"little"}'} spellCheck={false}/></label>{current&&<label>파일 추가<input aria-label="참조 파일 추가" type="file" multiple onChange={e=>{const files=Array.from(e.target.files||[]);e.target.value='';void upload(files);}}/></label>}</fieldset>}
 {current&&<article><header><h2>{current.title}</h2><p>{current.description}</p><small>{new Date(current.createdAt).toLocaleString()} · {current.blockIds.length?current.blockIds.map(id=>project.blocks.find(b=>b.id===id)?.name||id).join(' · '):'블록 연결 없음'}</small></header><details><summary>기록된 구현 · 메타데이터</summary><p>등록 시점 정보이며, 해당 구현이 파일을 생성했다는 자동 검증은 아닙니다.</p><pre>{JSON.stringify({checkpointId:current.checkpointId,...current.provenance,metadata:current.metadata},null,2)}</pre></details>
 <div className="work-controls"><button disabled={busy} onClick={()=>void download(`/reference-sets/${current.id}/export`,`${current.title.replace(/[<>:"/\\|?*]/g,'_')}.zip`)}><Download size={14}/> 입출력 세트 ZIP</button><button disabled={busy} onClick={()=>{if(confirm('참조 세트와 보관된 사본을 삭제할까요? 원본 파일은 유지됩니다.'))void run(async()=>{await api(`/reference-sets/${current.id}`,{updatedAt:current.updatedAt},'DELETE');setSelected('');await refresh();});}}><Trash2 size={14}/> 세트 삭제</button></div>
 {!current.files.length&&<p>아직 파일이 없습니다. 입력과 출력을 원하는 단위로 추가하세요.</p>}{current.files.map(f=><details key={f.id}><summary>{f.role==='input'?'입력':f.role==='output'?'출력':'기타'} · {f.name} · {(f.size/1024).toFixed(1)} KiB</summary><p>{f.description}</p><pre>{JSON.stringify(f.metadata,null,2)}</pre><small>SHA-256: {f.sha256}</small><button disabled={busy} onClick={()=>void download(`/reference-sets/${current.id}/files/${f.id}`,f.name)}>파일 다운로드</button></details>)}
 {current.files.length>=2&&<fieldset disabled={busy}><legend>파일 비교 (선택)</legend><p>사용자가 고른 두 파일의 바이트를 비교합니다. 다른 자료형·패킹은 먼저 변환해야 합니다.</p><label>기준<select aria-label="비교 기준 파일" value={expected} onChange={e=>{setExpected(e.target.value);setComparison(null);}}><option value="">선택</option>{current.files.map(f=><option key={f.id} value={f.id}>{f.name} · {f.role}</option>)}</select></label><label>대상<select aria-label="비교 대상 파일" value={actual} onChange={e=>{setActual(e.target.value);setComparison(null);}}><option value="">선택</option>{current.files.map(f=><option key={f.id} value={f.id}>{f.name} · {f.role}</option>)}</select></label><button disabled={!expected||!actual} onClick={()=>void run(async()=>setComparison(await api<Comparison>(`/reference-sets/${current.id}/compare`,{expectedId:expected,actualId:actual})))}>바이트 비교</button>{comparison&&<div role="status"><strong>{comparison.equal?'완전 일치':`${comparison.differentBytes.toLocaleString()}바이트 차이`}</strong><p>기준 {comparison.expectedBytes} bytes / 대상 {comparison.actualBytes} bytes</p><pre>{JSON.stringify(comparison.firstDifferences,null,2)}</pre></div>}</fieldset>}
 </article>}{!sets.length&&!creating&&<p>필요한 블록이나 구간만 기록하세요. 입력·출력 파일 수와 구현 구조는 자유입니다.</p>}{busy&&<p role="status">처리 중…</p>}
 </section>;
}
